# Generated by Django 5.1.4 on 2026-09-28 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_historia', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('CONEJO', 'Conejo'), ('ROEDOR', 'Roedor'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro')], max_length=10)),
                ('raza', models.CharField(blank=True, max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Puede ser aproximada', null=True)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('microchip', models.CharField(blank=True, max_length=30)),
                ('esterilizado', models.BooleanField(default=False)),
                ('alergias', models.TextField(blank=True, help_text='Se muestran destacadas en la ficha')),
                ('observaciones', models.TextField(blank=True)),
                ('fallecido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tutor', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nombre_mascota', models.CharField(max_length=60)),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('CONEJO', 'Conejo'), ('ROEDOR', 'Roedor'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro')], max_length=10)),
                ('fecha_preferida', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('acepta_datos', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de cita',
                'verbose_name_plural': 'Solicitudes de cita',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PAS', 'Pasaporte'), ('NIT', 'NIT')], default='CC', max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('autoriza_datos', models.BooleanField(default=False)),
                ('autoriza_datos_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tutores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('PRIMERA', 'Primera vez'), ('CONTROL', 'Control'), ('URGENCIA', 'Urgencia'), ('VACUNACION', 'Vacunación'), ('OTRO', 'Otro')], default='PRIMERA', max_length=12)),
                ('motivo', models.TextField()),
                ('anamnesis', models.TextField(blank=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, help_text='lpm', null=True)),
                ('frecuencia_respiratoria', models.PositiveSmallIntegerField(blank=True, help_text='rpm', null=True)),
                ('mucosas', models.CharField(blank=True, max_length=60)),
                ('tllc_segundos', models.DecimalField(blank=True, decimal_places=1, help_text='Tiempo de llenado capilar', max_digits=3, null=True)),
                ('hidratacion_pct', models.PositiveSmallIntegerField(blank=True, help_text='% de deshidratación', null=True)),
                ('condicion_corporal', models.PositiveSmallIntegerField(blank=True, help_text='Escala 1 a 9', null=True)),
                ('examen_fisico', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True, help_text='Presuntivo o definitivo')),
                ('plan', models.TextField(blank=True)),
                ('pronostico', models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('RESERVADO', 'Reservado'), ('DESFAVORABLE', 'Desfavorable')], max_length=12)),
                ('cerrada', models.BooleanField(default=False)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='clinica.paciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(help_text='Nombre comercial', max_length=120)),
                ('principio_activo', models.CharField(blank=True, max_length=120)),
                ('via', models.CharField(choices=[('ORAL', 'Oral'), ('SC', 'Subcutánea'), ('IM', 'Intramuscular'), ('IV', 'Intravenosa'), ('TOPICA', 'Tópica'), ('OFTALMICA', 'Oftálmica'), ('OTICA', 'Ótica'), ('OTRA', 'Otra')], default='ORAL', max_length=10)),
                ('dosis', models.CharField(help_text='Ej: "10 mg/kg" o "1 tableta"', max_length=60)),
                ('frecuencia', models.CharField(help_text='Ej: "cada 12 horas"', max_length=60)),
                ('duracion_dias', models.PositiveSmallIntegerField()),
                ('indicaciones', models.TextField(blank=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='clinica.consulta')),
            ],
            options={
                'verbose_name_plural': 'Prescripciones',
            },
        ),
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACUNA', 'Vacuna'), ('DESPARASITACION_INT', 'Desparasitación interna'), ('DESPARASITACION_EXT', 'Desparasitación externa')], max_length=20)),
                ('producto', models.CharField(max_length=120)),
                ('lote', models.CharField(blank=True, max_length=40)),
                ('aplicado_el', models.DateField(default=django.utils.timezone.localdate)),
                ('proxima_dosis', models.DateField(blank=True, db_index=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preventivos', to='clinica.paciente')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-aplicado_el'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='clinica.tutor'),
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(help_text='Matrícula profesional (COMVEZCOL)', max_length=40)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('foto', models.CharField(blank=True, max_length=200)),
                ('es_publico', models.BooleanField(default=True, help_text='Mostrar en la web pública')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Veterinarios',
            },
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(('microchip', ''), _negated=True), fields=('microchip',), name='microchip_unico_si_existe'),
        ),
    ]
