# Generated by Django 5.1.4 on 2026-10-04 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcita',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinica.consulta'),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinica.paciente'),
        ),
    ]
